### ISSUE TITLE
Clarify code quality control responsibilities

### ISSUE THREAD

**Issue by robertsawko** [ukgovdatascience/data_scientist_career_path#12]
Looking at ["Project and Programme Work"](https://github.com/ukgovdatascience/data_scientist_career_path/blob/master/index.md#project-and-programme-work-) it's slightly unclear to me who is providing code reviewing, assurance and to what extent. In this respect, I would suggest that the junior does basic code reviewing, data scientist reviews aspects specific to his specialty and higher roles make sure that the right processes and/or technologies are in place.

**Comment by DJHeron** [comment]
This was discussed in the workshop and the levels of mastery around programming should make it clear that Data Scientists should be working alongside other Technologists and depending on level of seniority will allocate code quality assurance tasks and define team practices.
