### ISSUE TITLE
The document doesn't mention legal aspects

### ISSUE THREAD

**Issue by robertsawko** [ukgovdatascience/data_scientist_career_path#13]
The issues related to open-source code, licensing etc are a common problem in software based industry. This should not interfere with the work of most people but it means there's someone, probably at a higher level, who's aware of the legal consequences of developing technology and provides an interface to legal specialists.

**Comment by DJHeron** [comment]
All roles within the Digital Data and Technology profession (and civil servants generally) should be aware of the need to escalate for legal opinion when required. The [Technology Code of Practice](https://www.gov.uk/government/publications/technology-code-of-practice/technology-code-of-practice) makes clear: 'If you’re designing, building or buying technology for a government organisation, you must follow these guidelines.' which includes routes for asking advice on these sorts of issues. Data Scientists would need to be aware of this as a professional responsibility.
