### ISSUE TITLE
Self-directed learning

### ISSUE THREAD

**Issue by robertsawko** [ukgovdatascience/data_scientist_career_path#14]
[Developing Data Science Capability](https://github.com/ukgovdatascience/data_scientist_career_path/blob/master/index.md#developing-data-science-capability) emphasizes self-directed learning which is good, I think, but may cause divergence of skills and knowledge. Some form of directed learning with verification of core skills should be incorporated.

I am not sure if certification programmes are the best solution here as they can quickly get outdated, but maybe some form of internal assessment of applying skills being developed within relevant projects.

**Comment by DJHeron** [comment]
This was discussed at the workshop and incorporated into the 'Data Science Innovation' capability section. It was also agreed that future iterations may draw on work such as the [Edison Project](http://edison-project.eu/data-science-competence-framework-cf-ds).
