### ISSUE TITLE
Career pathway diagram

### ISSUE THREAD

**Issue by MadelineLasko** [ukgovdatascience/data_scientist_career_path#2]
It might be a bit misleading to suggest that that the 'DDaT' Fast Stream would be a starting point for a career as a data scientist. The DaT scheme (at least currently) is a _specialist_ stream - not a _technical_ stream. There is no requirement for a technical background or a technical degree to qualify for the DaT scheme, and the vast majority of roles open to DaT Fast Streamers are generalist roles within digital or technology teams. If there is a Fast Stream which produces data scientists I'd have thought it would be Operational Research.

Having said that, there may be long term plans to change the emphasis of the Digital & Technology Fast Stream, including officially incorporating 'Data' into its title - turning it into the DDaT Fast Stream (a term which some people seem to have adopted already).

**Comment by DJHeron** [comment]
References to the DaT Fast Stream have been removed from the latest career path diagram. However, references to fast streamers from other professions may be added at a later date following implementation and iteration of the current version.
