### ISSUE TITLE
Concern on how the pathway feeds into the analytical professions.

### ISSUE THREAD

**Issue by myst3ria** [ukgovdatascience/data_scientist_career_path#9]
From the COI: Seems that there is a flow in from a postgrad degree, but can only flow out as you move up ranks. Whereas, there are a lot of lateral moves in and out of data science roles within the analytical professions. The roadmap generally does not seem very compatible with conventional analytical careers.

**Comment by DJHeron** [comment]
This should now be clearer in the new career path diagram.
